### ISSUE TITLE
Could not locate `icon-github.html` 

### ISSUE THREAD

**Issue by gryzzly** [ezrasavard/ezora-jekyll-theme#1]
Hey, I’m fairly new to Jekyll. I’ve added your theme to Gemfile and edited _config.yml to point at this theme. Running `bundle exec jekyll serve` blows up with the following:

``` sh
Configuration file: /Users/misha/Source/zhelam-jekyll/_config.yml
            Source: /Users/misha/Source/zhelam-jekyll
       Destination: /Users/misha/Source/zhelam-jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Could not locate the included file 'icon-github.html' in any of ["/Users/misha/Source/zhelam-jekyll/_includes", "/usr/local/lib/ruby/gems/2.3.0/gems/ezora-jekyll-theme-1.0.0/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in about.md
jekyll 3.2.1 | Error:  Could not locate the included file 'icon-github.html' in any of ["/Users/misha/Source/zhelam-jekyll/_includes", "/usr/local/lib/ruby/gems/2.3.0/gems/ezora-jekyll-theme-1.0.0/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.
```

**Comment by ezrasavard** [comment]
Hi Gryzzly, thanks for your comment. What you're seeing right now is that the "about.md" file that comes with a new Jekyll site looks for this GitHub icon that isn't included in my theme. This would be fixed when you replace about.md with your own content, but you'll likely run into other problems too.

I've decided not to support the Ruby Gems approach to Jekyll themes, since it has a lot of issues. So I think it would be better for you to fork my theme repository and build your site that way =)
